#!/bin/bash

# Setup script for connecting to GitHub

echo "🚀 Setting up daisy-ui GitHub repository"
echo ""
echo "Please follow these steps:"
echo ""
echo "1. Go to https://github.com/new"
echo "2. Create a new repository named 'daisy-ui'"
echo "3. Set it as Public or Private based on your preference"
echo "4. DO NOT initialize with README, .gitignore, or license"
echo "5. After creating, run these commands:"
echo ""
echo "# Add the remote origin (replace YOUR_USERNAME with your GitHub username)"
echo "git remote add origin https://github.com/YOUR_USERNAME/daisy-ui.git"
echo ""
echo "# Push to GitHub"
echo "git branch -M main"
echo "git push -u origin main"
echo ""
echo "6. For Firebase Studio:"
echo "   - Go to https://studio.firebase.google.com"
echo "   - Import from GitHub"
echo "   - Select your daisy-ui repository"
echo "   - Firebase Studio will automatically detect the project structure"
echo ""
echo "Optional: If you want to use GitHub token for authentication:"
echo "git remote set-url origin https://YOUR_TOKEN@github.com/YOUR_USERNAME/daisy-ui.git"